/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.34.1
 * source: event.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
/* eslint-disable @typescript-eslint/no-namespace, @typescript-eslint/no-explicit-any */
export namespace event {
    export class Event extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            type?: string;
            data?: Map<string, string>;
            timestamp?: number;
            latency_trace?: Map<string, number>;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("type" in data && data.type != undefined) {
                    this.type = data.type;
                }
                if ("data" in data && data.data != undefined) {
                    this.data = data.data;
                }
                if ("timestamp" in data && data.timestamp != undefined) {
                    this.timestamp = data.timestamp;
                }
                if ("latency_trace" in data && data.latency_trace != undefined) {
                    this.latency_trace = data.latency_trace;
                }
            }
            if (!this.data)
                this.data = new Map();
            if (!this.latency_trace)
                this.latency_trace = new Map();
        }
        get type() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set type(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get data() {
            return pb_1.Message.getField(this, 2) as any as Map<string, string>;
        }
        set data(value: Map<string, string>) {
            pb_1.Message.setField(this, 2, value as any);
        }
        get timestamp() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set timestamp(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get latency_trace() {
            return pb_1.Message.getField(this, 4) as any as Map<string, number>;
        }
        set latency_trace(value: Map<string, number>) {
            pb_1.Message.setField(this, 4, value as any);
        }
        static fromObject(data: {
            type?: string;
            data?: {
                [key: string]: string;
            };
            timestamp?: number;
            latency_trace?: {
                [key: string]: number;
            };
        }): Event {
            const message = new Event({});
            if (data.type != null) {
                message.type = data.type;
            }
            if (typeof data.data == "object") {
                message.data = new Map(Object.entries(data.data));
            }
            if (data.timestamp != null) {
                message.timestamp = data.timestamp;
            }
            if (typeof data.latency_trace == "object") {
                message.latency_trace = new Map(Object.entries(data.latency_trace));
            }
            return message;
        }
        toObject() {
            const data: {
                type?: string;
                data?: {
                    [key: string]: string;
                };
                timestamp?: number;
                latency_trace?: {
                    [key: string]: number;
                };
            } = {};
            if (this.type != null) {
                data.type = this.type;
            }
            if (this.data != null) {
                data.data = (Object.fromEntries)(this.data);
            }
            if (this.timestamp != null) {
                data.timestamp = this.timestamp;
            }
            if (this.latency_trace != null) {
                data.latency_trace = (Object.fromEntries)(this.latency_trace);
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.type.length)
                writer.writeString(1, this.type);
            for (const [key, value] of this.data) {
                writer.writeMessage(2, this.data, () => {
                    writer.writeString(1, key);
                    writer.writeString(2, value);
                });
            }
            if (this.timestamp != 0)
                writer.writeDouble(3, this.timestamp);
            for (const [key, value] of this.latency_trace) {
                writer.writeMessage(4, this.latency_trace, () => {
                    writer.writeString(1, key);
                    writer.writeDouble(2, value);
                });
            }
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Event {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Event();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.type = reader.readString();
                        break;
                    case 2:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.data as any, reader, reader.readString, reader.readString));
                        break;
                    case 3:
                        message.timestamp = reader.readDouble();
                        break;
                    case 4:
                        reader.readMessage(message, () => pb_1.Map.deserializeBinary(message.latency_trace as any, reader, reader.readString, reader.readDouble));
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Event {
            return Event.deserialize(bytes);
        }
    }
}
