# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protobuf/event.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'protobuf/event.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protobuf/event.proto\x12\x05\x65vent\"\xe7\x01\n\x05\x45vent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12$\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x16.event.Event.DataEntry\x12\x11\n\ttimestamp\x18\x03 \x01(\x01\x12\x35\n\rlatency_trace\x18\x04 \x03(\x0b\x32\x1e.event.Event.LatencyTraceEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x33\n\x11LatencyTraceEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protobuf.event_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT_DATAENTRY']._loaded_options = None
  _globals['_EVENT_DATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENT_LATENCYTRACEENTRY']._loaded_options = None
  _globals['_EVENT_LATENCYTRACEENTRY']._serialized_options = b'8\001'
  _globals['_EVENT']._serialized_start=32
  _globals['_EVENT']._serialized_end=263
  _globals['_EVENT_DATAENTRY']._serialized_start=167
  _globals['_EVENT_DATAENTRY']._serialized_end=210
  _globals['_EVENT_LATENCYTRACEENTRY']._serialized_start=212
  _globals['_EVENT_LATENCYTRACEENTRY']._serialized_end=263
# @@protoc_insertion_point(module_scope)
